# https://blog.csdn.net/yangshangwei/article/details/122889066
spring:
  cloud:
    gateway: #gateway
      routes:
        - id: just4Test
          uri: http://spring.io
          predicates:
            - Path=/projects
          filters:
            - AddResponseHeader=X-Request-Company, Artisan

